# -*- coding: utf-8 -*-
"""Mobilenet with pseudocolor enhancement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mq1UKBFo6Nwbq_f6rh8KzR6Dg8zo19OO

# Kidney disease detection
"""

from google.colab import drive
drive.mount('/content/drive')

# Dataset paths
dataset_path = "/content/drive/MyDrive/Final Kidney CT Images"
cyst_path = "/content/drive/MyDrive/Final Kidney CT Images/Cyst"
stone_path = "/content/drive/MyDrive/Final Kidney CT Images/Stone"
normal_path = "/content/drive/MyDrive/Final Kidney CT Images/Normal"
img_size = (150, 150)

classes = ["Cyst","Stone","Normal"]

"""**Import Files**"""

import cv2
import os
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import time
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, BatchNormalization, Reshape, multiply
from tensorflow.keras.models import Model
from tensorflow.keras import optimizers
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

"""**Image Preprocessing**"""

# Step 3: Image Preprocessing Function
def preprocess_pipeline(img):
    """
    Apply a 3-step preprocessing pipeline:
    1. Noise Removal (Median Blur)
    2. Contrast Enhancement (CLAHE)
    3. Edge Enhancement (Sobel)
    """
    # 1. Noise Removal
    median_img = cv2.medianBlur(img, 3)

    # 2. Contrast Enhancement
    gray = cv2.cvtColor(median_img, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    clahe_img = clahe.apply(gray)

    # 3. Edge Enhancement
    sobelx = cv2.Sobel(clahe_img, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(clahe_img, cv2.CV_64F, 0, 1, ksize=3)
    sobel_img = cv2.magnitude(sobelx, sobely)
    sobel_img = cv2.convertScaleAbs(sobel_img)

    # Convert single channel to RGB
    clahe_img_rgb = cv2.cvtColor(clahe_img, cv2.COLOR_GRAY2RGB)
    sobel_img_rgb = cv2.cvtColor(sobel_img, cv2.COLOR_GRAY2RGB)

    return median_img, clahe_img_rgb, sobel_img_rgb

# Step 4: Load dataset with preprocessing + pseudo-color
X_processed, y_processed = [], []

for idx, cls in enumerate(classes):
    cls_path = os.path.join(dataset_path, cls)
    for img_file in os.listdir(cls_path):
        img_path = os.path.join(cls_path, img_file)

        # 1. Load image
        img = cv2.imread(img_path)
        img = cv2.resize(img, img_size)

        # 2. Apply preprocessing
        median_img, clahe_img, sobel_img = preprocess_pipeline(img)

        # >>> Use CLAHE output as the processed version <<<
        processed_img = clahe_img

        # 3. Normalize to [0,1]
        processed_img = processed_img / 255.0

        # 4. Append to dataset
        X_processed.append(processed_img)
        y_processed.append(idx)

# Convert to NumPy arrays
X_processed = np.array(X_processed, dtype=np.float32)
y_processed = np.array(y_processed)

print("Shape of X_processed:", X_processed.shape)
print("Shape of y_processed:", y_processed.shape)

# Visualization of preprocessing effects
plt.figure(figsize=(16, 8))
plot_idx = 1

for cls in classes:
    cls_path = os.path.join(dataset_path, cls)
    img_file = os.listdir(cls_path)[0]  # pick one sample image
    img_path = os.path.join(cls_path, img_file)

    img = cv2.imread(img_path)
    img = cv2.resize(img, img_size)

    # Apply preprocessing
    median_img, clahe_img, sobel_img = preprocess_pipeline(img)

    imgs_to_plot = [img, median_img, clahe_img, sobel_img]
    titles = ["Original", "Median Blur", "CLAHE", "Sobel Edge"]

    for vis_img, title in zip(imgs_to_plot, titles):
        plt.subplot(len(classes), 4, plot_idx)
        if len(vis_img.shape) == 2:
            plt.imshow(vis_img, cmap='gray')
        else:
            plt.imshow(cv2.cvtColor(vis_img, cv2.COLOR_BGR2RGB))
        plt.title(f"{cls} - {title}")
        plt.axis('off')
        plot_idx += 1

plt.tight_layout()
plt.show()

"""**[Pseudocolor Enhancement]**"""

# Function to apply pseudo color
def apply_pseudo_color(img):
    return cv2.applyColorMap(img, cv2.COLORMAP_JET)

# Dictionary of class paths
classes_paths = {
    "Cyst": cyst_path,
    "Stone": stone_path,
    "Normal": normal_path
}

num_images = 5  # per class

plt.figure(figsize=(20, 12))

plot_idx = 1
for cls_name, cls_path in classes_paths.items():
    img_files = os.listdir(cls_path)[:num_images]
    for img_file in img_files:
        img_path = os.path.join(cls_path, img_file)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (150, 150))
        img = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

        # Pseudo-color version
        pseudo_img = apply_pseudo_color(img)

        # Show original grayscale
        plt.subplot(len(classes_paths), num_images*2, plot_idx)
        plt.imshow(img, cmap='gray')
        plt.title(f"{cls_name} - Original")
        plt.axis('off')
        plot_idx += 1

        # Show pseudo-color
        plt.subplot(len(classes_paths), num_images*2, plot_idx)
        plt.imshow(cv2.cvtColor(pseudo_img, cv2.COLOR_BGR2RGB))
        plt.title(f"{cls_name} - Pseudo Color")
        plt.axis('off')
        plot_idx += 1

plt.tight_layout()
plt.show()

def apply_pseudo_color(img):
    return cv2.applyColorMap(img, cv2.COLORMAP_JET)

X_pseudo, y_pseudo = [], []

for idx, cls in enumerate(classes):
    cls_path = os.path.join(dataset_path, cls)
    for img_file in os.listdir(cls_path):
        img_path = os.path.join(cls_path, img_file)

        # Load grayscale
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, img_size)
        img = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

        # Apply pseudo-color
        pseudo_img = apply_pseudo_color(img)
        pseudo_img = cv2.cvtColor(pseudo_img, cv2.COLOR_BGR2RGB)  # BGR → RGB

        # Normalize to [0,1]
        pseudo_img = pseudo_img / 255.0

        X_pseudo.append(pseudo_img)
        y_pseudo.append(idx)

X_pseudo = np.array(X_pseudo, dtype=np.float32)
y_pseudo = np.array(y_pseudo)

print("Shape of X_pseudo:", X_pseudo.shape)
print("Shape of y_pseudo:", y_pseudo.shape)

"""**Data Splitting**"""

# 80% train, 20% temp
X_train, X_temp, y_train, y_temp = train_test_split(
    X_pseudo, y_pseudo, test_size=0.2, random_state=123, stratify=y_pseudo
)

# Split temp → 10% validation, 10% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=123, stratify=y_temp
)

print("Train:", X_train.shape, y_train.shape)
print("Validation:", X_val.shape, y_val.shape)
print("Test:", X_test.shape, y_test.shape)

batch_size = 16

train_ds = tf.data.Dataset.from_tensor_slices((X_train, y_train)).shuffle(100).batch(batch_size)
val_ds   = tf.data.Dataset.from_tensor_slices((X_val, y_val)).batch(batch_size)
test_ds  = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(batch_size)

"""**Augmentation on pseudocolor segmented images**"""

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.03),  # ±10 degrees
    layers.RandomZoom(0.1, 0.1),
    layers.RandomTranslation(0.1, 0.1),
    layers.RandomContrast(0.1),
    layers.GaussianNoise(0.01)
])

for images, labels in train_ds.take(1):
    augmented_images = data_augmentation(images)

    plt.figure(figsize=(12,6))
    for i in range(6):
        # Original pseudo-color
        plt.subplot(2,6,i+1)
        orig_img = tf.clip_by_value(images[i], 0.0, 1.0).numpy()  # clip to [0,1]
        plt.imshow(orig_img.astype(np.float32))
        plt.title(f"Original: {labels[i].numpy()}")
        plt.axis("off")

        # Augmented pseudo-color
        plt.subplot(2,6,i+7)
        aug_img = tf.clip_by_value(augmented_images[i], 0.0, 1.0).numpy()  # clip to [0,1]
        plt.imshow(aug_img.astype(np.float32))
        plt.title("Augmented")
        plt.axis("off")
    plt.show()

"""**SE-MobKidNet or** **AttenKidNet**"""

# SE Attention block
def se_block(input_tensor, ratio=16):
    filters = input_tensor.shape[-1]
    se = GlobalAveragePooling2D()(input_tensor)
    se = Reshape((1, 1, filters))(se)
    se = Dense(filters // ratio, activation='relu')(se)
    se = Dense(filters, activation='sigmoid')(se)
    return multiply([input_tensor, se])

# Base Model
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(150, 150, 3))
base_model.trainable = False

# Add Attention + Classifier Head
x = se_block(base_model.output)
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.4)(x)
output = Dense(3, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=optimizers.AdamW(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Early stopping
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Reduce LR if val_loss plateaus
lr_reduce = ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=3, verbose=1, min_lr=1e-6)

##train the model
start_time = time.time()  # Start timer

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=[early_stop, lr_reduce]
)

end_time = time.time()  # End timer

training_time = end_time - start_time
print(f"Total training time: {training_time:.2f} seconds")
print(f"Which is approximately: {training_time/60:.2f} minutes")

# Measure testing time
test_start = time.time()

test_loss, test_accuracy = model.evaluate(test_ds, verbose=1)

test_end = time.time()

testing_time = test_end - test_start
print(f"\nTest Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"Total Testing Time: {testing_time:.2f} seconds ({testing_time/60:.2f} minutes)")

"""**Apply Confusion Matrix**"""

# Get True Labels and Predictions
y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

y_true = np.array(y_true)
y_pred = np.array(y_pred)

print("True Labels Shape:", y_true.shape)
print("Predicted Labels Shape:", y_pred.shape)

y_pred = []
y_true = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_pred.extend(np.argmax(preds, axis=1))
    y_true.extend(labels.numpy())

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred, target_names=classes))

# Ensure y_true and y_pred exist
# If they don't, run the prediction loop from Step 13 again
# Example:
# y_true = np.array(y_true)
# y_pred = np.array(y_pred)

# Create the confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Plot heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=classes,
            yticklabels=classes)

plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix')
plt.show()

# Ensure y_true and y_pred are numpy arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Compute per-class metrics
class_accuracies = {}
class_precisions = precision_score(y_true, y_pred, average=None)
class_recalls = recall_score(y_true, y_pred, average=None)
class_f1s = f1_score(y_true, y_pred, average=None)

for i, cls in enumerate(classes):
    # Mask for current class
    class_mask = (y_true == i)

    # Compute accuracy manually
    correct = np.sum((y_true[class_mask] == y_pred[class_mask]))
    total = np.sum(class_mask)
    class_acc = correct / total if total > 0 else 0

    class_accuracies[cls] = {
        "Accuracy": class_acc,
        "Precision": class_precisions[i],
        "Recall": class_recalls[i],
        "F1-score": class_f1s[i],
    }

# Display results in table
df = pd.DataFrame(class_accuracies).T
print(df)

# Get all test images and labels
X_test_all = np.concatenate([x for x, y in test_ds], axis=0)
y_test_all = np.concatenate([y for x, y in test_ds], axis=0)

# Get predictions
y_pred_probs = model.predict(test_ds)
y_pred_all = np.argmax(y_pred_probs, axis=1)

# Show 5 images per class
num_images = 5

plt.figure(figsize=(15, 9))

for i, cls in enumerate(classes):
    # Find indices of this class in the test set
    idxs = np.where(y_test_all == i)[0][:num_images]  # take first 5 images
    for j, idx in enumerate(idxs):
        plt.subplot(len(classes), num_images, i*num_images + j + 1)
        plt.imshow(X_test_all[idx])
        plt.title(f"A: {classes[y_test_all[idx]]}\nP: {classes[y_pred_all[idx]]}")
        plt.axis("off")

plt.suptitle("Actual vs Predicted Images per Class", fontsize=16)
plt.tight_layout()
plt.show()